import os

print("==================================================================")
print("                      INSTALLATION PACKAGES                       ")
print("==================================================================")
print("perintah ini akan meng-install paket berikut:                     ")
print("            Packages             |           VERSION              ")
print("            numpy+mkl            |           1.11.2               ")
print("            six                  |           1.10.0               ")
print("            pyparsing            |           2.1..10              ")
print("            pytz                 |           2016.7               ")
print("            cycler               |           0.10.0               ")
print("            python_dateutil      |           2.6.0                ")
print("            matplotlib           |           1.5.3                ")
print("            scipy                |           0.18.1               ")
print("            PyOpenGL             |           3.1.1                ")
print("            Pillow               |           3.4.2                ")
print("            opencv_python        |           3.1.0                ")
print("            sip                  |           4.18.1               ")
print("            PyQt5                |           5.7                  ")
print("            pyqt5_tools          |           5.7.dev9             ")
print("==================================================================")
pilihan = input("Lanjutkan installasi? (y/n)")

if(pilihan=="y"):
 print("==================================================================")
 print("[    Begin   ]: Installing packages")
 print("==================================================================")

 print("\n==================================================================")
 print("[ Installing ]: numpy-1.11.2+mkl-cp35-cp35m-win32.whl")
 print("==================================================================")
 os.system("python -m pip install \"numpy-1.11.2+mkl-cp35-cp35m-win32.whl\"")

 print("\n==================================================================")
 print("[ Installing ]: six-1.10.0-py2.py3-none-any.whl")
 print("==================================================================")
 os.system("python -m pip install six-1.10.0-py2.py3-none-any.whl")

 print("\n==================================================================")
 print("[ Installing ]: pyparsing-2.1.10-py2.py3-none-any.whl")
 print("==================================================================")
 os.system("python -m pip install pyparsing-2.1.10-py2.py3-none-any.whl")

 print("\n==================================================================")
 print("[ Installing ]: pytz-2016.7-py2.py3-none-any.whl")
 print("==================================================================")
 os.system("python -m pip install pytz-2016.7-py2.py3-none-any.whl")

 print("\n==================================================================")
 print("[ Installing ]: cycler-0.10.0-py2.py3-none-any.whl")
 print("==================================================================")
 os.system("python -m pip install cycler-0.10.0-py2.py3-none-any.whl")

 print("\n==================================================================")
 print("[ Installing ]: python_dateutil-2.6.0-py2.py3-none-any.whl")
 print("==================================================================")
 os.system("python -m pip install python_dateutil-2.6.0-py2.py3-none-any.whl")

 print("\n==================================================================")
 print("[ Installing ]: matplotlib-1.5.3-cp35-cp35m-win32.whl")
 print("==================================================================")
 os.system("python -m pip install matplotlib-1.5.3-cp35-cp35m-win32.whl")

 print("\n==================================================================")
 print("[ Installing ]: scipy-0.18.1-cp35-cp35m-win32.whl")
 print("==================================================================")
 os.system("python -m pip install scipy-0.18.1-cp35-cp35m-win32.whl")

 print("\n==================================================================")
 print("[ Installing ]: PyOpenGL-3.1.1-cp35-cp35m-win32.whl")
 print("==================================================================")
 os.system("python -m pip install PyOpenGL-3.1.1-cp35-cp35m-win32.whl")

 print("\n==================================================================")
 print("[ Installing ]: Pillow-3.4.2-cp35-cp35m-win32.whl")
 print("==================================================================")
 os.system("python -m pip install Pillow-3.4.2-cp35-cp35m-win32.whl")

 print("\n==================================================================")
 print("[ Installing ]: opencv_python-3.1.0-cp35-cp35m-win32.whl")
 print("==================================================================")
 os.system("python -m pip install opencv_python-3.1.0-cp35-cp35m-win32.whl")

 print("\n==================================================================")
 print("[ Installing ]: sip-4.18.1-cp35-none-win32.whl")
 print("==================================================================")
 os.system("python -m pip install sip-4.18.1-cp35-none-win32.whl")

 print("\n==================================================================")
 print("[ Installing ]: PyQt5-5.7-cp35-none-win32.whl")
 print("==================================================================")
 os.system("python -m pip install PyQt5-5.7-cp35-none-win32.whl")

 print("\n==================================================================")
 print("[ Installing ]: pyqt5_tools-5.7.dev9-cp35-none-win32.whl")
 print("==================================================================")
 os.system("python -m pip install pyqt5_tools-5.7.dev9-cp35-none-win32.whl")

 print("\n==================================================================")
 print("[    End     ]: Finish")
 print("==================================================================")
 print("press any key to continue...")
 x = input("")
